### ISSUE TITLE
Allow save/load of inactive characters

### ISSUE THREAD

**Issue by WMSkyfall** [Sebaestschjin/gloomhaven-campaign-manager#63]
My Gloomhaven group has a few party members who don't get brought on every scenario (player alternate characters and guest characters). These party members have equipment and personal goals, both of which reduce the general supply, but they don't fit in the active 4-player roster and are not saved with the campaign manager. When loading our game state to a new copy of the mod, I need to copy the inactive characters as Saved Objects and manually delete their duplicate equipped items from the shop.

Would it be possible for the campaign manager to process inactive (boxed) characters into the save file, and then create them in a boxed state somewhere on the table when the save file is loaded? Perhaps there could be an "Inactive Characters" mat somewhere on the table, and any character boxes sitting on that mat when the user clicked "Save" would be saved with the campaign manager.

(I love the mod, BTW. We've been playing on an old version of Gloomhaven Fantasy UI and I just finished using your mod to migrate our campaign to the freshest version. It's a relief to not have to deal with migrating a few dozen Saved Objects!)

**Comment by Sebaestschjin** [comment]
Yeah, that would be a very nice feature. I didn't touch that yet, because it was tricky to do as you can't access objects within a box, so you would have to unpack it, wait until that is done and then check the objects. However, with the knowledge I have now about TTS it should be also possible to do so while the objects are boxed, just hadn't the time yet to fully test it.

**Comment by Sebaestschjin** [comment]
Phew, finally got this working. :-)
Inactive characters are now saved and loaded as well. If you have an already packed character in your save, you have to unpack and repack it again. The reason is that the buttons for adding and removing characters are changed through this mod. Only when packing a character with this new version of the buttons can an inactive character be stored. Otherwise it won't be found.
