### ISSUE TITLE
Missing attack modifier cards after load

### ISSUE THREAD

**Issue by bestekov** [Sebaestschjin/gloomhaven-campaign-manager#65]
Some player base attack modifier cards appear to just be gone. Notably, `-1` cards that were removed by armor.

**Comment by Sebaestschjin** [comment]
The modifier cards from persk are automatically removed from the deck and the cards are destroyed. The `-1` cards from armor are dealt on top of the armor item, unless the character has the perks that negates negative card effects. There's #51 that will change the removal of modifier cards so that they are kept and not destroyed. Or do you mean something else?

**Comment by bestekov** [comment]
Thank you, that explains it. So, if we retire and make a new character, how does one get back the destroyed cards? Or does creating a new character generate a new deck? (We have so far not unlocked any new characters).

**Comment by Sebaestschjin** [comment]
Yes, when you create a new character (by pulling out the mini box from the bigger one) there's always a new deck of modifier cards in the box.
