### ISSUE TITLE
How do you get coordinates for enhancements?

### ISSUE THREAD

**Issue by Fyren** [Sebaestschjin/gloomhaven-campaign-manager#85]
The GH scripted setup authors also have a mod for the FH kickstarter stuff that includes character envelopes for the JotL classes.  You can move those envelopes over to the GH mod and they work.  I was looking at adding support for them in your tool and it looks straightforward except for the coordinates of the enhancements.  

I guess they're local coordinates on the card?  Is there a way to get them besides doing something like adding a decal on top of them and then scripting something to get the coordinates of that decals?

**Comment by Sebaestschjin** [comment]
Yes, those are the local coordinates for the cards. I have a helper script that generates those for me (look at the [Enhancement Helper](https://github.com/Sebaestschjin/gloomhaven-campaign-manager/blob/master/gloomhaven-campaign-manager/EnhancementHelper.ttslua).
My workflow for that is: Attach the numbered decals on the ability cards. Move the ability cards onto the object with the EnhancementHelper script. This prints to name of the ability as well as the locations of the decals into the game window in the same format that is required by the `Game` module. This can also be copied from the Atom console and is ready to go. Only the level of the ability has to be adjusted as it only prints zero. Also for some reason, when copying from the Atom console, there are some weird non-printable whitespace characters as well. Those have to be removed as well, otherwise adding the script to TTS won't work.
